### ISSUE TITLE
Tests do not compile on Windows (syscall.Kill in httplisten_test.go)

### ISSUE THREAD

**Issue by farhansabbir** [dmartsapp/shint#13]
`go vet ./...` and `go test ./...` fail to build the tests for Windows:

```
$ GOOS=windows GOARCH=amd64 go vet ./...
vet: lib/handlers/httplisten_test.go:228:20: undefined: syscall.Kill
```

The other release targets (freebsd, openbsd, netbsd, solaris) compile the tests fine. The shipped `shint.windows.*.exe` binaries are not affected (the file is a test file); this only means the test suite cannot run on Windows.

**Fix:** put the signal-sending tests behind `//go:build !windows` (or use a portable way to interrupt the listener), then check the other test files with `GOOS=windows go vet ./...`.

**Why it matters:** the CI job planned for v4.1.0 runs `make check`; without this the suite can only run on Unix runners.

---
Opened by Claude (Claude Code), working on shint with @farhansabbir.

**Comment by farhansabbir** [comment]
Working on this in v4.1.0 (branch `release/v4.1.0`). Plan: move the SIGINT-sending into a small test helper with a Unix and a Windows version, so the three "runs until interrupted" tests (http, tcp, udp listen) compile everywhere and skip on Windows, where a test process cannot signal itself this way.

---
Claude (Claude Code)

**Comment by farhansabbir** [comment]
Fix is on `release/v4.1.0`: dmartsapp/shint@498706a. `GOOS=windows go vet ./...` now passes, and `make vet` runs it (plus freebsd and solaris) so this cannot regress. The three interrupt tests are skipped on Windows. It will be closed when v4.1.0 is released.

---
Claude (Claude Code)

**Comment by farhansabbir** [comment]
**Resolved in v4.2.0** (released 2026-09-21). The fix was made for v4.1.0, which was released together with v4.2.0 (v4.2.0 includes everything planned for v4.1.0).

| | |
|---|---|
| Present in | v4.0.0 to v4.0.6 |
| Fixed in | v4.1.0's changes, shipped in v4.2.0 |
| How this was checked | `GOOS=windows go vet ./...` fails with `syscall.Kill` on every tag from v4.0.0 to v4.0.6 (the shipped binaries were never affected: it is the test suite); it passes on v4.2.0 |

_Checked by building each release and running it - v4.1.0 from its release commit a512969, because it was released together with v4.2.0 and never tagged separately. What was run is in the row above._
